### PR TITLE
Feature/rockets fetch display

### PR DESCRIPTION
**Pull request by PinkMoon25**
#### In this PR I have :

- Written actions and reducers to fetch rockets data from the API
- Configured store for rockets data
- Added provider component in the app
- Rendered the list of rockets in the page
- Added reduxjs toolkit and redux-thunk

### CODE REVIEW

**Review by TracK92 — COMMENTED** [review]
I have reviewed your work.

**Review by TracK92 — APPROVED** [review]
**Hi @PinkMoon25 ,**

# Status: APPROVED 🏆 🎉

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚀: 
Congratulations! 🎉 

## To highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The project is working as expected
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

Alt Text


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by PinkMoon25** [comment]
Thanks @TracK92 for the review 👍

**Review by AckonSamuel — APPROVED** [review]
Hi @PinkMoon25 ,

Good job implementing the project requirements :+1: 
There is nothing else to say other than it is time to merge it :shipit:
congrats :tada:

**Pull request merged**
