### PR TITLE
Test/mission

### PR DESCRIPTION
**Pull request by AckonSamuel**
In this milestone, these changes were implemented:

<hr>

- [x] Add tests for my_profile component
- [x] Add tests for missions component

### CODE REVIEW

**Review by TracK92 — CHANGES_REQUESTED** [review]
Hi  @AckonSamuel  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
- The tests are failing on my end. Kindly adjust them accordingly. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

**Comment by AckonSamuel** [comment]
the test are working perfectly on my end here

**Comment by AckonSamuel** [comment]
@TracK92 
 After you do `npm i`, do` npm run start`

**Comment by TracK92** [comment]
@AckonSamuel , when I run `npm test,` all the tests are failing.

**Comment by AckonSamuel** [comment]
> @AckonSamuel , when I run `npm test,` all the tests are failing.

Kindly add  screenshots of the log messages

**Comment by TracK92** [comment]
image

- This is what I'm getting on my end when I run your tests. We can meet up in the afternoon and discuss the discrepancy.

**Review by TracK92 — APPROVED** [review]
Hi @AckonSamuel, 👋🏻👋🏻
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada: 



#### Highlights :sparkle: 

:heavy_check_mark:  No Linters error 
:heavy_check_mark: The project works as expected
:heavy_check_mark: good commit history
:heavy_check_mark: nice PR description

Cheers and Happy coding! :clap: :clap: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Review by PinkMoon25 — APPROVED** [review]
Hi @AckonSamuel, 👋🏻👋🏻
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! tada



#### Highlights :sparkles: 

:heavy_check_mark: All tests are passing
:heavy_check_mark: No Linters error
:heavy_check_mark: The project works as expected

Cheers and Happy coding! 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Pull request merged**
